language: bash
dist: trusty
os: linux

addons:
  apt:
    packages:
      - libxml2-utils
      - shunit2
      - git

servies:
  - docker

before_script:
  - cd data && curl "http://diglib.lib.utk.edu/dlc/standards/tei/tei_lite_di_v3.rng" > tei_lite_di_v3.rng
  - cd ../
  - echo "$(git rev-parse --abbrev-ref HEAD)" && git rev-parse --abbrev-ref HEAD

script:
  - cd tests
  - ./validate_polk.sh
  - ./test_build.sh