language: bash
dist: trusty
os: linux

addons:
  apt:
    packages:
      - libxml2-utils
      - shunit2

before_script:
  - cd data && curl "http://diglib.lib.utk.edu/dlc/standards/tei/tei_lite_di_v3.rng" > tei_lite_di_v3.rng
  - cd ../

script:
  - cd tests
  - source "validate_polk.sh"
