language: bash
dist: trusty
os: linux

addons:
  apt:
    packages:
      - libxml2-utils
      - shunit2

before_script:
  - curl -L "http://downloads.sourceforge.net/shunit2/shunit2-2.0.3.tgz" > data/shunit2-2.0.3.tgz
  - cd data && tar -xzvf shunit2-2.0.3.tgz
  - curl "http://diglib.lib.utk.edu/dlc/standards/tei/tei_lite_di_v3.rng" > tei_lite_di_v3.rng

script:
  - cd tests && ./validate_polk.sh
